"""excel_config

Revision ID: 440fe3b08b3f
Revises: 6fe5e9d4a144
Create Date: 2026-06-22 05:55:11.527932
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '440fe3b08b3f'
down_revision = '6fe5e9d4a144'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboards', sa.Column('excel_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dashboards', 'excel_config')
    # ### end Alembic commands ###
