"""folders

Revision ID: d952b8e473ad
Revises: 440fe3b08b3f
Create Date: 2026-06-23 23:56:51.666576
"""
from alembic import op
import sqlalchemy as sa


revision = 'd952b8e473ad'
down_revision = '440fe3b08b3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folder',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('dashboards', sa.Column('folder_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_dashboards_folder_id'), 'dashboards', ['folder_id'], unique=False)
    op.create_foreign_key(None, 'dashboards', 'folder', ['folder_id'], ['id'], ondelete='SET NULL')

    # Data migration: promote existing group_name labels to first-class folders
    # (alphabetical position) and link each dashboard to its folder.
    op.execute(
        """
        INSERT INTO folder (id, name, position, created_at)
        SELECT gen_random_uuid(), g.name,
               row_number() OVER (ORDER BY g.name) - 1,
               now()
        FROM (
            SELECT DISTINCT group_name AS name
            FROM dashboards
            WHERE group_name IS NOT NULL AND btrim(group_name) <> ''
        ) g
        """
    )
    op.execute(
        """
        UPDATE dashboards d
        SET folder_id = f.id
        FROM folder f
        WHERE d.group_name = f.name
        """
    )

    op.drop_column('dashboards', 'group_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboards', sa.Column('group_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'dashboards', type_='foreignkey')
    op.drop_index(op.f('ix_dashboards_folder_id'), table_name='dashboards')
    op.drop_column('dashboards', 'folder_id')
    op.drop_table('folder')
    # ### end Alembic commands ###
